const users = [
  {
    username: "admin_user",
    email: "admin@example.com",
    fullname: "System Administrator",
    password: "Password123",
    role: "admin",
  },
  {
    username: "noah97",
    email: "noah97@example.com",
    fullname: "Noah Rodriguez",
    password: "Password123",
    role: "user",
  },
  {
    username: "aarav34",
    email: "aarav34@example.com",
    fullname: "Aarav Taylor",
    password: "Password123",
    role: "user",
  },
  {
    username: "carlos74",
    email: "carlos74@example.com",
    fullname: "Carlos Lopez",
    password: "Password123",
    role: "user",
  },
  {
    username: "noah99",
    email: "noah99@example.com",
    fullname: "Noah Hernandez",
    password: "Password123",
    role: "user",
  },
  {
    username: "ethan16",
    email: "ethan16@example.com",
    fullname: "Ethan Wilson",
    password: "Password123",
    role: "user",
  },
  {
    username: "ivan75",
    email: "ivan75@example.com",
    fullname: "Ivan Garcia",
    password: "Password123",
    role: "user",
  },
  {
    username: "aarav12",
    email: "aarav12@example.com",
    fullname: "Aarav Taylor",
    password: "Password123",
    role: "user",
  },
  {
    username: "ethan86",
    email: "ethan86@example.com",
    fullname: "Ethan Gonzalez",
    password: "Password123",
    role: "user",
  },
  {
    username: "kevin17",
    email: "kevin17@example.com",
    fullname: "Kevin Wilson",
    password: "Password123",
    role: "user",
  },
  {
    username: "kevin31",
    email: "kevin31@example.com",
    fullname: "Kevin Sharma",
    password: "Password123",
    role: "user",
  },
  {
    username: "diana18",
    email: "diana18@example.com",
    fullname: "Diana Chen",
    password: "Password123",
    role: "user",
  },
  {
    username: "ivan19",
    email: "ivan19@example.com",
    fullname: "Ivan Taylor",
    password: "Password123",
    role: "user",
  },
  {
    username: "noah11",
    email: "noah11@example.com",
    fullname: "Noah Wilson",
    password: "Password123",
    role: "user",
  },
  {
    username: "hannah20",
    email: "hannah20@example.com",
    fullname: "Hannah Martinez",
    password: "Password123",
    role: "user",
  },
];

export { users };
